export const ENDPOINTS = {
  users: '/users',
  platformSettings: '/platformSettings',
  user: (userId: number) => `/users/${userId}`,
  wallets: (userId: number) => `/wallets?userId=${userId}`,
  orders: (userId: number, type: string) => `/orders?userId=${userId}&type=${type}`,
  transactions: (userId: number) => `/transactions?userId=${userId}`,
  tradeHistory: (userId: number) => `/tradeHistory?userId=${userId}`,
  botTrades: (userId: number) => `/botTrades?userId=${userId}`,
  botTradeById: (id: string) => `/botTrades/${id}`,
  botSettings: (userId: number) => `/botSettings?userId=${userId}`,
  botSettingById: (id: number) => `/botSettings/${id}`,
  marketStats: '/marketStats',
  deposits: (userId: number) => `/deposits?userId=${userId}`,
  depositsAll: '/deposits',
  holdings: (userId: number) => `/holdings?userId=${userId}`,
  holdingsAll: '/holdings',
  holdingById: (id: number) => `/holdings/${id}`,
  profitOverview: (userId: number) => `/profitOverview?userId=${userId}`,
  purchases: (userId: number) => `/purchases?userId=${userId}`,
  purchasesAll: '/purchases',
  userNotifications: (userId: number) => `/userNotifications?userId=${userId}`,
  userNotificationById: (id: number) => `/userNotifications/${id}`,
  userNotificationsMarkAllRead: (userId: number) => `/userNotifications/mark-all-read?userId=${userId}`,
  notifications: (userId: number) => `/notifications?userId=${userId}`,
  notificationById: (id: number) => `/notifications/${id}`,
  kyc: '/kyc',
  kycMe: '/kyc/me',
}
